//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testConexion1_cerberus.BISAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", ConfigurationName="BISAService.aqua")]
    public interface aqua {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación purchasePOSATC no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        testConexion1_cerberus.BISAService.purchasePOSATCResponse1 purchasePOSATC(testConexion1_cerberus.BISAService.purchasePOSATCRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.purchasePOSATCResponse1> purchasePOSATCAsync(testConexion1_cerberus.BISAService.purchasePOSATCRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación cancelOrQuestPOSATC no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse1 cancelOrQuestPOSATC(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse1> cancelOrQuestPOSATCAsync(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación version no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        testConexion1_cerberus.BISAService.versionResponse1 version(testConexion1_cerberus.BISAService.versionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.versionResponse1> versionAsync(testConexion1_cerberus.BISAService.versionRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class purchasePOSATCRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private string movilNumberField;
        
        private string smsPINField;
        
        private decimal amountField;
        
        private string currencyField;
        
        private string commerceField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string movilNumber {
            get {
                return this.movilNumberField;
            }
            set {
                this.movilNumberField = value;
                this.RaisePropertyChanged("movilNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string smsPIN {
            get {
                return this.smsPINField;
            }
            set {
                this.smsPINField = value;
                this.RaisePropertyChanged("smsPIN");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string commerce {
            get {
                return this.commerceField;
            }
            set {
                this.commerceField = value;
                this.RaisePropertyChanged("commerce");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class purchasePOSATCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private string cardNumberField;
        
        private System.DateTime expirationField;
        
        private bool expirationFieldSpecified;
        
        private string codeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("cardNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
                this.RaisePropertyChanged("expiration");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationSpecified {
            get {
                return this.expirationFieldSpecified;
            }
            set {
                this.expirationFieldSpecified = value;
                this.RaisePropertyChanged("expirationSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class purchasePOSATCRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public testConexion1_cerberus.BISAService.purchasePOSATCRequest purchasePOSATCRequest;
        
        public purchasePOSATCRequest1() {
        }
        
        public purchasePOSATCRequest1(testConexion1_cerberus.BISAService.purchasePOSATCRequest purchasePOSATCRequest) {
            this.purchasePOSATCRequest = purchasePOSATCRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class purchasePOSATCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public testConexion1_cerberus.BISAService.purchasePOSATCResponse purchasePOSATCResponse;
        
        public purchasePOSATCResponse1() {
        }
        
        public purchasePOSATCResponse1(testConexion1_cerberus.BISAService.purchasePOSATCResponse purchasePOSATCResponse) {
            this.purchasePOSATCResponse = purchasePOSATCResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class cancelOrQuestPOSATCRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private cancelOrQuestPOSATCRequestCause causeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public cancelOrQuestPOSATCRequestCause cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
                this.RaisePropertyChanged("cause");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public enum cancelOrQuestPOSATCRequestCause {
        
        /// <comentarios/>
        C,
        
        /// <comentarios/>
        Q,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class cancelOrQuestPOSATCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private string cardNumberField;
        
        private System.DateTime expirationField;
        
        private bool expirationFieldSpecified;
        
        private string codeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("cardNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
                this.RaisePropertyChanged("expiration");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationSpecified {
            get {
                return this.expirationFieldSpecified;
            }
            set {
                this.expirationFieldSpecified = value;
                this.RaisePropertyChanged("expirationSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelOrQuestPOSATCRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest;
        
        public cancelOrQuestPOSATCRequest1() {
        }
        
        public cancelOrQuestPOSATCRequest1(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest) {
            this.cancelOrQuestPOSATCRequest = cancelOrQuestPOSATCRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelOrQuestPOSATCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse cancelOrQuestPOSATCResponse;
        
        public cancelOrQuestPOSATCResponse1() {
        }
        
        public cancelOrQuestPOSATCResponse1(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse cancelOrQuestPOSATCResponse) {
            this.cancelOrQuestPOSATCResponse = cancelOrQuestPOSATCResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.bisa.com/schema/aqua/version")]
    public partial class versionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="versionRequest", Namespace="http://xml.bisa.com/schema/aqua/version", Order=0)]
        public object versionRequest1;
        
        public versionRequest() {
        }
        
        public versionRequest(object versionRequest1) {
            this.versionRequest1 = versionRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xml.bisa.com/schema/aqua/version", Order=0)]
        public testConexion1_cerberus.BISAService.versionResponse versionResponse;
        
        public versionResponse1() {
        }
        
        public versionResponse1(testConexion1_cerberus.BISAService.versionResponse versionResponse) {
            this.versionResponse = versionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface aquaChannel : testConexion1_cerberus.BISAService.aqua, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class aquaClient : System.ServiceModel.ClientBase<testConexion1_cerberus.BISAService.aqua>, testConexion1_cerberus.BISAService.aqua {
        
        public aquaClient() {
        }
        
        public aquaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public aquaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public aquaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public aquaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testConexion1_cerberus.BISAService.purchasePOSATCResponse1 testConexion1_cerberus.BISAService.aqua.purchasePOSATC(testConexion1_cerberus.BISAService.purchasePOSATCRequest1 request) {
            return base.Channel.purchasePOSATC(request);
        }
        
        public testConexion1_cerberus.BISAService.purchasePOSATCResponse purchasePOSATC(testConexion1_cerberus.BISAService.purchasePOSATCRequest purchasePOSATCRequest) {
            testConexion1_cerberus.BISAService.purchasePOSATCRequest1 inValue = new testConexion1_cerberus.BISAService.purchasePOSATCRequest1();
            inValue.purchasePOSATCRequest = purchasePOSATCRequest;
            testConexion1_cerberus.BISAService.purchasePOSATCResponse1 retVal = ((testConexion1_cerberus.BISAService.aqua)(this)).purchasePOSATC(inValue);
            return retVal.purchasePOSATCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.purchasePOSATCResponse1> testConexion1_cerberus.BISAService.aqua.purchasePOSATCAsync(testConexion1_cerberus.BISAService.purchasePOSATCRequest1 request) {
            return base.Channel.purchasePOSATCAsync(request);
        }
        
        public System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.purchasePOSATCResponse1> purchasePOSATCAsync(testConexion1_cerberus.BISAService.purchasePOSATCRequest purchasePOSATCRequest) {
            testConexion1_cerberus.BISAService.purchasePOSATCRequest1 inValue = new testConexion1_cerberus.BISAService.purchasePOSATCRequest1();
            inValue.purchasePOSATCRequest = purchasePOSATCRequest;
            return ((testConexion1_cerberus.BISAService.aqua)(this)).purchasePOSATCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse1 testConexion1_cerberus.BISAService.aqua.cancelOrQuestPOSATC(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1 request) {
            return base.Channel.cancelOrQuestPOSATC(request);
        }
        
        public testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse cancelOrQuestPOSATC(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest) {
            testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1 inValue = new testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1();
            inValue.cancelOrQuestPOSATCRequest = cancelOrQuestPOSATCRequest;
            testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse1 retVal = ((testConexion1_cerberus.BISAService.aqua)(this)).cancelOrQuestPOSATC(inValue);
            return retVal.cancelOrQuestPOSATCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse1> testConexion1_cerberus.BISAService.aqua.cancelOrQuestPOSATCAsync(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1 request) {
            return base.Channel.cancelOrQuestPOSATCAsync(request);
        }
        
        public System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.cancelOrQuestPOSATCResponse1> cancelOrQuestPOSATCAsync(testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest) {
            testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1 inValue = new testConexion1_cerberus.BISAService.cancelOrQuestPOSATCRequest1();
            inValue.cancelOrQuestPOSATCRequest = cancelOrQuestPOSATCRequest;
            return ((testConexion1_cerberus.BISAService.aqua)(this)).cancelOrQuestPOSATCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testConexion1_cerberus.BISAService.versionResponse1 testConexion1_cerberus.BISAService.aqua.version(testConexion1_cerberus.BISAService.versionRequest request) {
            return base.Channel.version(request);
        }
        
        public testConexion1_cerberus.BISAService.versionResponse version(object versionRequest1) {
            testConexion1_cerberus.BISAService.versionRequest inValue = new testConexion1_cerberus.BISAService.versionRequest();
            inValue.versionRequest1 = versionRequest1;
            testConexion1_cerberus.BISAService.versionResponse1 retVal = ((testConexion1_cerberus.BISAService.aqua)(this)).version(inValue);
            return retVal.versionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.versionResponse1> testConexion1_cerberus.BISAService.aqua.versionAsync(testConexion1_cerberus.BISAService.versionRequest request) {
            return base.Channel.versionAsync(request);
        }
        
        public System.Threading.Tasks.Task<testConexion1_cerberus.BISAService.versionResponse1> versionAsync(object versionRequest1) {
            testConexion1_cerberus.BISAService.versionRequest inValue = new testConexion1_cerberus.BISAService.versionRequest();
            inValue.versionRequest1 = versionRequest1;
            return ((testConexion1_cerberus.BISAService.aqua)(this)).versionAsync(inValue);
        }
    }
}
